---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.5
before_install: gem install bundler -v 2.0.2
script:
  - bundle exec rspec
  - bundle exec rake report:reassemble
  - bundle exec rake report:rerun
  - bundle exec rake report:endtoend
